version: '3.9'
services:
	redis:
		image: redis:7-alpine
		ports:
			- "6379:6379"
	worker:
		build:
			context: .
			dockerfile: Dockerfile.worker
		environment:
			REDIS_URL: redis://redis:6379
			NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
			SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
			AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
			AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME}
			AZURE_STORAGE_ACCOUNT_KEY: ${AZURE_STORAGE_ACCOUNT_KEY}
		depends_on:
			- redis
